// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAjNiThumBobK46BRb2ySQmUengK2_fB5o",
      authDomain: "tswcd-8e055.firebaseapp.com",
      databaseURL: "https://tswcd-8e055-default-rtdb.firebaseio.com",
      projectId: "tswcd-8e055",
      storageBucket: "tswcd-8e055.appspot.com",
      messagingSenderId: "982692893418",
      appId: "1:982692893418:web:f6971433f030ee58367d93",
      measurementId: "G-78XSQNW0B0"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlGuZpsFyFqjln06uoN7cOJvZNXw5KbxI',
    appId: '1:982692893418:android:f7d7031e18e84451367d93',
    messagingSenderId: '982692893418',
    projectId: 'tswcd-8e055',
    storageBucket: 'tswcd-8e055.appspot.com',
  );
}
